### PR TITLE
Update pooling data, adding verbosity

### PR DESCRIPTION
**Pull request by damianfedeczko**
Fix a bug:
- pull internal IP instead of external IP for Virtual Machines, based on client request
Enhance logging:
- added more verbosity to the Cloud Function by adding more logging info and substituting some of the pieces already in place

### CODE REVIEW

**Comment by damianfedeczko** [comment]
I've tested the external IP to internal IP switch inline in the Cloud Function, the Datastore was updated with internal IPs.

**Review by devsecfranklin — CHANGES_REQUESTED** [review]
Can you add "keybank_gcp_tagging" as funciton name in config.ini? 

Also change the username to "panapiuser" for Panorama in config.ini

**Comment by damianfedeczko** [comment]
> Can you add "keybank_gcp_tagging" as funciton name in config.ini?
> 
> Also change the username to "panapiuser" for Panorama in config.ini

Sure, I was thinking about adding this, wasn't sure if we want to do it right now, but since the testing is now done in KeyBank env, you are absolutely right. I'm just not used to not having a way to do some stuff on my own :/

**Comment by devsecfranklin** [comment]
> > Can you add "keybank_gcp_tagging" as funciton name in config.ini?
> > Also change the username to "panapiuser" for Panorama in config.ini
> 
> Sure, I was thinking about adding this, wasn't sure if we want to do it right now, but since the testing is now done in KeyBank env, you are absolutely right. I'm just not used to not having a way to do some stuff on my own :/

Yes testing will have to be done in their env from now on I think. Baby taking the first steps!

**Comment by damianfedeczko** [comment]
@devsecfranklin  are we sure about the username? is it `panapiuser` or `apiuser`?

**Comment by devsecfranklin** [comment]
> @devsecfranklin are we sure about the username? is it `panapiuser` or `apiuser`?

I have `panapiuser` in my notes from yesterday. Thanks for double checking.

**Review by devsecfranklin — APPROVED** [review]
LGTM

**Pull request merged**
